let products = [
  {
    link: "single_page.html",
    name: "Mango People jacket№1",
    price: "10.00",
    imageSrc: "img/products/product_13.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People jacket№2",
    price: "20.00",
    imageSrc: "img/products/product_14.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People jacket№3",
    price: "30.00",
    imageSrc: "img/products/product_15.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "",
      "",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People T-shirt",
    price: "40.00",
    imageSrc: "img/products/product_16.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People sweater",
    price: "50.00",
    imageSrc: "img/products/product_17.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "",
      "",
      "",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People jacket",
    price: "60.00",
    imageSrc: "img/products/product_18.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "",
      "",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People Blazer",
    price: "70.00",
    imageSrc: "img/products/product_19.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People jacket",
    price: "85.00",
    imageSrc: "img/products/product_20.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "",
      "",
    ],
  },
  {
    link: "single_page.html",
    name: "Mango People T-shirt№2",
    price: "100.00",
    imageSrc: "img/products/product_21.jpg",
    rating: [
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
      "products__item-stars_golden",
    ],
  },
];

export default products;
